projects:
  civic:
    schemaPath: src/graphql/schema.json
    includes:
      - database.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
